// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import appPackage from '../../package.json';

export const environment = {
  production: false,
  hmr: true,
  version: appPackage.version + '-dev',
  x_api_key: 'hCFf3S3^F9S58&DbKeScU77DX$5YpWXvvv76u8w&WfTPAtpyGRCTU5*TNxEBrh^Rt#$U#B!3gBDa@4eTXjF!*Bg#Q6cJ@c!$2&^4',
  ip_api_secret: 'c5449b3b65dd96712cdc5178c0db3ab5cf336d09f55ad4bfa07dc098',
  serverUrl: 'http://localhost:3000/api/v2',
  serverSamlUrl: 'https://xgrowth-server-test.azurewebsites.net',
  websiteUrl: 'https://xgrowth-server-test.azurewebsites.net',
  defaultLanguage: 'pt-BR',
  supportedLanguages: ['en-US', 'fr-FR', 'pt-BR']
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
