// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import appPackage from '../../package.json';

export const environment = {
  production: false,
  version: appPackage.version + '-demo',
  x_api_key: 'cqEfY3#W8nF6kX55Z3QGaREe5FwaKhb*#Up*$5UCRDRS#vmNFnG4yNUqktsrJAjQ7Yktz!Ns4%YE*&z$Rx2V9rRkHW$dke2sjMgh',
  ip_api_secret: 'c5449b3b65dd96712cdc5178c0db3ab5cf336d09f55ad4bfa07dc098',
  serverUrl: 'https://xgrowth-server-test.azurewebsites.net/api/v2',
  websiteUrl: 'https://xgrowth-server-test.azurewebsites.net',
  serverSamlUrl: 'https://xgrowth-server-test.azurewebsites.net',
  defaultLanguage: 'pt-BR',
  supportedLanguages: ['en-US', 'pt-BR']
};
