// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import appPackage from '../../package.json';

export const environment = {
  production: true,
  hmr: false,
  version: appPackage.version,
  x_api_key: '&#77%Mf2W7cGvzR7QMmzpdKU@XRb^anuJuXdfRCggDMCeghQV6$QKEqwNbbyQXKwxJcmwbhUGdQAzysA2PB5u!y@2R8w#@XT!*7z',
  ip_api_secret: 'c5449b3b65dd96712cdc5178c0db3ab5cf336d09f55ad4bfa07dc098',
  serverUrl: 'https://xgrowth-server-prod.azurewebsites.net/api/v2',
  websiteUrl: 'https://xgrowth-server-prod.azurewebsites.net',
  serverSamlUrl: 'https://xgrowth-server-prod.azurewebsites.net',
  defaultLanguage: 'pt-BR',
  supportedLanguages: ['en-US', 'pt-BR']
};
